Repository SwArch-2025-1-2A/auth, pull requests merged in 2025-05, with the labels that each got.

#1 Initialize project
  .dockerignore
  .env.sample
  Dockerfile
  LICENSE
  README.md
  docker-compose.yml
  eslint.config.mjs
  package-lock.json
  package.json
  prisma/migrations/20250517085331_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/app.ts
  src/index.ts
  tsconfig.json
Labels: documentation, enhancement

#3 Fix problems with authentication database
  docker-compose.yml
Labels: bug

#4 Add table of contents
  README.md
Labels: documentation

#8 Standarize microservice
  .dockerignore
  .env.example
  .env.sample
  .prodignore
  Dockerfile
  README.md
  docker-compose.yml
Labels: documentation, enhancement, Docker

#9 Make hostname configurable from `.env`
  .env.example
Labels: bug, enhancement, Docker

#5 Signup progress
  package-lock.json
  package.json
  src/app.ts
  src/interfaces/interfaces.ts
  src/routes/signup.ts
Labels: enhancement

#10 Auth progress
  .env.example
  docker-compose.yml
  src/app.ts
  src/middlewares/auth_middleware.ts
  src/routes/auth_me.ts
  src/routes/login.ts
Labels: enhancement
